name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        if: github.event_name == 'pull_request'
        uses: ikmdev/maven-pull-request-version-validation-action@main
        
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
        
      - name: Build Protoc Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: protoc.dockerfile
          tags: tinkar-schema-protoc:latest

      - name: Generate Java Code
        run: |
          docker run -v ./src/main/java-generated:/home/proto-builder/src/main/java-generated --rm tinkar-schema-protoc:latest
      
      - name: list java code
        run: |
          ls src/main/java-generated

      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}

    
